# Generated by Django 5.0 on 2023-12-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('instrument', models.CharField(choices=[('guitar', 'Guitar'), ('piano', 'Piano'), ('violin', 'Violin'), ('drums', 'Drums')], max_length=10)),
            ],
        ),
    ]
